# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e353db77d0002b5c6eff76c050724028c4d06fc7f7c52b9494ce48ad26cff9aecfe4154e78c4a756fc62d427ded723629974b67edc86061f37568ad229d83d9a

test:
  secret_key_base: b97556972d860823408c20aee7151e10b6165e512dda1db932ae32ae82f109473cc234245d380979ba9587b02e22077ad0dec0b59107efdc964cf20c4b42cd13

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
